spring:
  h2:
    console:
      path: /h2-console
      enabled: true
      generate-unique-name: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090